//! Reference Cloudflare Workers host for cfml-worker.
//!
//! Wires:
//! - `#[event(fetch)]` → [`cfml_worker::handle_fetch`]
//! - `#[event(scheduled)]` → [`cfml_worker::handle_scheduled`] (cron sweep
//!   of expired KV sessions → `onSessionEnd`)
//! - `#[durable_object] ApplicationScopeDO` → strong-consistency
//!   application-scope storage that
//!   [`cfml_worker::DoApplicationStore`] talks to via JSPI.
//!
//! Templates: copy this directory, edit `wrangler.toml` bindings, drop
//! your CFML under `cfml/`, deploy with `wrangler deploy`.

#![cfg(target_arch = "wasm32")]

use worker::*;

// Generated by build.rs from the cfml/ directory.
include!(concat!(env!("OUT_DIR"), "/embedded_files.rs"));

/// Virtual root the CFML VM sees as its filesystem root. Paths in
/// `CFML_FILES` are stored relative to this.
const VIRTUAL_ROOT: &str = "/app";

/// Name of the Application.cfc `this.name` we prime from the app store.
/// Keep in sync with the sample `cfml/Application.cfc`.
const APP_NAME: &str = "rustcfml-worker-demo";

fn build_config(env: &Env) -> cfml_worker::WorkerConfig {
    let mut config = cfml_worker::WorkerConfig::new(CFML_FILES, VIRTUAL_ROOT);
    config.app_names = vec![APP_NAME.to_string()];

    if let Ok(kv) = env.kv("SESSIONS") {
        config.kv_sessions = Some(kv);
    }
    if let Ok(kv) = env.kv("APP") {
        config.kv_application = Some(kv);
    }
    // DO wins over KV when present.
    if let Ok(ns) = env.durable_object("APP_DO") {
        config.do_application = Some(ns);
    }

    // Hyperdrive datasources. Each binding name is exposed to CFML as the
    // `datasource="..."` attribute on <cfquery>. The JS shim sniffs the
    // binding's connectionString prefix (`postgres://` vs `mysql://`) and
    // dispatches via postgres.js or mysql2/promise accordingly.
    for name in ["HYPERDRIVE_PG", "HYPERDRIVE_MYSQL"] {
        if let Ok(binding) = env.hyperdrive(name) {
            config
                .hyperdrive_datasources
                .push((name.to_string(), std::sync::Arc::new(binding)));
        }
    }

    config
}

#[event(fetch)]
pub async fn fetch(req: Request, env: Env, ctx: Context) -> Result<Response> {
    let config = build_config(&env);
    cfml_worker::handle_fetch(req, env, ctx, &config).await
}

// Re-export the JSPI smoke-test entry points so wasm-opt doesn't drop them.
// The post-build patch wraps `cfml_worker_jspi_smoke` in
// `WebAssembly.promising` and exposes it on `globalThis.__cfmlJspi.smoke`
// to validate that JSPI suspend/resume works from a clean sync wasm
// activation (i.e. without going through the wasm-bindgen-futures-driven
// `#[event(fetch)]`).
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn cfml_worker_jspi_smoke() {
    cfml_worker::jspi_smoke::cfml_worker_jspi_smoke();
}

#[wasm_bindgen]
pub fn cfml_worker_jspi_smoke_take() -> String {
    cfml_worker::jspi_smoke::cfml_worker_jspi_smoke_take()
}

// Sync VM runner. The post-build patch wraps this in
// `WebAssembly.promising` and exposes it as `globalThis.__cfmlJspi.runSync`,
// which the async `handle_fetch` invokes after staging a `RunContext`.
// Re-exported here so wasm-opt keeps it in the final cdylib.
#[wasm_bindgen]
pub fn cfml_worker_run_sync() {
    cfml_worker::sync_runner::cfml_worker_run_sync();
}

#[event(scheduled)]
pub async fn scheduled(event: ScheduledEvent, env: Env, ctx: ScheduleContext) {
    let config = build_config(&env);
    let _ = cfml_worker::handle_scheduled(event, env, ctx, &config).await;
}

/// Durable Object backing strong-consistency application scope.
///
/// One DO instance per `idFromName(<app_name>)` so the single-instance
/// request serialization gives atomic put-after-get for the contained
/// `(variables, started)` blob. The JSON shape matches
/// `cfml_worker::do_application_store::PersistedApp`.
#[durable_object]
pub struct ApplicationScopeDO {
    state: State,
}

impl DurableObject for ApplicationScopeDO {
    fn new(state: State, _env: Env) -> Self {
        Self { state }
    }

    async fn fetch(&self, mut req: Request) -> Result<Response> {
        let storage = self.state.storage();
        match (req.method(), req.path().as_str()) {
            (Method::Get, "/get") => match storage.get::<String>("body").await {
                Ok(Some(body)) => Response::ok(body),
                _ => Response::error("not found", 404),
            },
            (Method::Post, "/put") => {
                let body = req.text().await?;
                storage.put("body", body).await?;
                Ok(Response::empty()?.with_status(204))
            }
            _ => Response::error("not found", 404),
        }
    }
}
