//! Cloudflare Worker entry point.
//!
//! Almost all of the logic now lives in the `cfml-worker` crate that ships
//! with RustCFML. This file just provides the embedded CFML file table
//! (generated by `build.rs`) and the bindings glue.

use cfml_worker::{handle_fetch, WorkerConfig};
use std::sync::Arc;
use worker::{event, Context, Env, Request, Response, Result};

include!(concat!(env!("OUT_DIR"), "/cfml_files.rs"));

#[event(fetch)]
pub async fn main(req: Request, env: Env, ctx: Context) -> Result<Response> {
    let mut config = WorkerConfig::new(CFML_FILES, "/app");
    config.app_names = vec!["rustcfml-worker".into()];

    if let Ok(kv) = env.kv("SESSIONS") {
        config.kv_sessions = Some(kv);
    }
    if let Ok(kv) = env.kv("APPLICATION") {
        config.kv_application = Some(kv);
    }
    if let Ok(db) = env.d1("DB") {
        config.d1_datasources.push(("main".into(), Arc::new(db)));
    }

    handle_fetch(req, env, ctx, &config).await
}
