use std::collections::{HashMap, HashSet};
use std::io;
use std::sync::Arc;
use std::time::SystemTime;

use cfml_common::vm::CfmlResult;

use cfml_codegen::compiler::CfmlCompiler;
use cfml_common::dynamic::CfmlValue;
use cfml_common::vfs::{VfsDirEntry, Vfs};
use cfml_compiler::{parser::Parser, tag_parser};
use cfml_stdlib::builtins::{get_builtin_functions, get_builtins};
use cfml_vm::CfmlVirtualMachine;
use indexmap::IndexMap;
use worker::*;

// Generated by build.rs — all files from cfml/ embedded at compile time.
include!(concat!(env!("OUT_DIR"), "/cfml_files.rs"));

// Virtual path prefix the VM sees as its filesystem root.
const VIRTUAL_ROOT: &str = "/app";

// ---------------------------------------------------------------------------
// Embedded VFS
//
// Mirrors EmbeddedFs from cfml-common but uses SystemTime::UNIX_EPOCH for
// mtime. Cloudflare Workers (wasm32-unknown-unknown) panics on SystemTime::now()
// because the platform has no system clock — only JS Date.now() is available.
// The mtime is only used for bytecode-cache invalidation; a fixed value is
// fine because our embedded files never change between requests.
// ---------------------------------------------------------------------------

struct WorkerVfs {
    files: HashMap<String, Vec<u8>>,
    dirs:  HashSet<String>,
    base_dir: String,
}

impl WorkerVfs {
    fn new(raw: HashMap<String, Vec<u8>>, base_dir: String) -> Self {
        let mut files = HashMap::new();
        let mut dirs  = HashSet::new();
        dirs.insert(String::new());

        for (path, data) in raw {
            let norm = Self::norm_static(&path);
            // Register every ancestor directory
            let mut cur = String::new();
            for seg in norm.split('/') {
                if !cur.is_empty() { cur.push('/'); }
                cur.push_str(seg);
                if cur != norm { dirs.insert(cur.clone()); }
            }
            files.insert(norm, data);
        }
        Self { files, dirs, base_dir }
    }

    fn norm_static(path: &str) -> String {
        path.replace('\\', "/").trim_start_matches('/').to_lowercase()
    }

    fn norm(&self, path: &str) -> String {
        let path = path.replace('\\', "/");
        let stripped = if !self.base_dir.is_empty() {
            let base = self.base_dir.replace('\\', "/").to_lowercase();
            if path.to_lowercase().starts_with(&base) {
                path[self.base_dir.len()..].trim_start_matches('/').to_lowercase()
            } else {
                path.trim_start_matches('/').to_lowercase()
            }
        } else {
            path.trim_start_matches('/').to_lowercase()
        };
        let mut parts: Vec<&str> = Vec::new();
        for seg in stripped.split('/') {
            match seg { "." | "" => {} ".." => { parts.pop(); } s => parts.push(s) }
        }
        parts.join("/")
    }
}

impl Vfs for WorkerVfs {
    fn read_to_string(&self, path: &str) -> io::Result<String> {
        let n = self.norm(path);
        self.files.get(&n)
            .map(|d| String::from_utf8_lossy(d).to_string())
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, format!("not found: {path}")))
    }
    fn read(&self, path: &str) -> io::Result<Vec<u8>> {
        let n = self.norm(path);
        self.files.get(&n).cloned()
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, format!("not found: {path}")))
    }
    fn exists(&self, path: &str) -> bool {
        let n = self.norm(path);
        self.files.contains_key(&n) || self.dirs.contains(&n)
    }
    fn is_file(&self, path: &str) -> bool { self.files.contains_key(&self.norm(path)) }
    fn is_dir(&self, path: &str)  -> bool { self.dirs.contains(&self.norm(path)) }

    fn read_dir(&self, path: &str) -> io::Result<Vec<VfsDirEntry>> {
        let n = self.norm(path);
        if !self.dirs.contains(&n) {
            return Err(io::Error::new(io::ErrorKind::NotFound, format!("dir not found: {path}")));
        }
        let prefix = if n.is_empty() { String::new() } else { format!("{n}/") };
        let mut seen = HashSet::new();
        let mut entries = Vec::new();
        for fp in self.files.keys() {
            if fp.starts_with(&prefix) {
                let rest = &fp[prefix.len()..];
                if let Some(p) = rest.find('/') {
                    let name = rest[..p].to_string();
                    if seen.insert(name.clone()) {
                        entries.push(VfsDirEntry { name, is_file: false, is_dir: true });
                    }
                } else {
                    entries.push(VfsDirEntry { name: rest.to_string(), is_file: true, is_dir: false });
                }
            }
        }
        Ok(entries)
    }

    // Fixed epoch — no SystemTime::now() here; Workers has no system clock.
    fn modified(&self, path: &str) -> io::Result<SystemTime> {
        if self.files.contains_key(&self.norm(path)) {
            Ok(SystemTime::UNIX_EPOCH)
        } else {
            Err(io::Error::new(io::ErrorKind::NotFound, "not found"))
        }
    }

    fn canonicalize(&self, path: &str) -> io::Result<String> {
        let n = self.norm(path);
        if self.files.contains_key(&n) || self.dirs.contains(&n) {
            Ok(if self.base_dir.is_empty() { format!("/{n}") } else { format!("{}/{n}", self.base_dir) })
        } else {
            Err(io::Error::new(io::ErrorKind::NotFound, format!("not found: {path}")))
        }
    }
}

fn build_vfs() -> Arc<WorkerVfs> {
    let files: HashMap<String, Vec<u8>> = CFML_FILES
        .iter()
        .map(|(path, bytes)| (path.to_string(), bytes.to_vec()))
        .collect();
    Arc::new(WorkerVfs::new(files, VIRTUAL_ROOT.to_string()))
}

// ---------------------------------------------------------------------------
// Path → CFM file resolution
// ---------------------------------------------------------------------------

/// Maps an HTTP path to a cfm file path in the embedded VFS.
/// Returns the relative path (e.g. "about.cfm", "blog/post.cfm").
fn resolve_cfm(http_path: &str) -> Option<&'static str> {
    let clean = http_path.trim_start_matches('/');

    // Candidate list: bare path, then index fallback
    let candidates: &[String] = &if clean.is_empty() {
        vec!["index.cfm".to_string()]
    } else {
        vec![
            format!("{clean}.cfm"),
            format!("{clean}/index.cfm"),
        ]
    };

    for candidate in candidates {
        for (file_path, _) in CFML_FILES {
            if file_path.to_lowercase() == candidate.to_lowercase() {
                return Some(file_path);
            }
        }
    }

    None
}

// ---------------------------------------------------------------------------
// Request context helpers
// ---------------------------------------------------------------------------

fn parse_query(query: &str) -> IndexMap<String, CfmlValue> {
    url::form_urlencoded::parse(query.as_bytes())
        .map(|(k, v)| (k.to_lowercase(), CfmlValue::String(v.to_string())))
        .collect()
}

fn parse_form_body(body: &str) -> IndexMap<String, CfmlValue> {
    url::form_urlencoded::parse(body.as_bytes())
        .map(|(k, v)| (k.to_lowercase(), CfmlValue::String(v.to_string())))
        .collect()
}

fn build_cgi_scope(req: &Request) -> IndexMap<String, CfmlValue> {
    let mut cgi: IndexMap<String, CfmlValue> = IndexMap::new();

    let method = req.method().to_string();
    let path = req.path();

    cgi.insert("request_method".into(), CfmlValue::String(method.clone()));
    cgi.insert("path_info".into(), CfmlValue::String(path.clone()));
    cgi.insert("script_name".into(), CfmlValue::String(path));
    cgi.insert("server_protocol".into(), CfmlValue::String("HTTP/1.1".into()));
    cgi.insert("server_software".into(), CfmlValue::String("RustCFML/Cloudflare-Workers".into()));
    cgi.insert("gateway_interface".into(), CfmlValue::String("CGI/1.1".into()));

    if let Ok(parsed_url) = req.url() {
        let host = parsed_url.host_str().unwrap_or("").to_string();
        let qs   = parsed_url.query().unwrap_or("").to_string();
        cgi.insert("http_host".into(),      CfmlValue::String(host.clone()));
        cgi.insert("server_name".into(),    CfmlValue::String(host));
        cgi.insert("query_string".into(),   CfmlValue::String(qs));
    }

    let headers = req.headers();
    for key in ["content-type", "content-length", "accept", "user-agent", "referer", "accept-language"] {
        if let Ok(Some(val)) = headers.get(key) {
            let cgi_key = format!("http_{}", key.replace('-', "_"));
            cgi.insert(cgi_key, CfmlValue::String(val));
        }
    }

    if let Ok(Some(ct)) = headers.get("content-type") {
        cgi.insert("content_type".into(), CfmlValue::String(ct));
    }
    if let Ok(Some(cl)) = headers.get("content-length") {
        cgi.insert("content_length".into(), CfmlValue::String(cl));
    }

    cgi
}

// ---------------------------------------------------------------------------
// Platform builtins
//
// Some cfml-stdlib functions call SystemTime::now() internally, which panics
// on wasm32-unknown-unknown (Cloudflare Workers has no system clock).
// We replace them with implementations backed by JS Date.now().
// ---------------------------------------------------------------------------

// Cloudflare Workers clamps performance.now() to ~1ms resolution (Spectre mitigation).
// We read it from Rust around the whole execute() call so the window is as wide as
// possible. performance.now() returns milliseconds as f64; × 1_000_000 → nanoseconds.
#[cfg(target_arch = "wasm32")]
fn perf_now_ns() -> i64 {
    use wasm_bindgen::{JsCast, JsValue};
    let global = js_sys::global();
    let perf = js_sys::Reflect::get(&global, &JsValue::from_str("performance"))
        .unwrap_or(JsValue::NULL);
    let now_fn = js_sys::Reflect::get(&perf, &JsValue::from_str("now"))
        .unwrap_or(JsValue::NULL);
    now_fn
        .dyn_ref::<js_sys::Function>()
        .and_then(|f| f.call0(&perf).ok())
        .and_then(|v| v.as_f64())
        .map(|ms| (ms * 1_000_000.0) as i64)
        .unwrap_or(0)
}

#[cfg(not(target_arch = "wasm32"))]
fn perf_now_ns() -> i64 { 0 }

// getTickCount() still works for CFML code that calls it directly.
#[cfg(target_arch = "wasm32")]
fn builtin_gettickcount(_args: Vec<CfmlValue>) -> CfmlResult {
    Ok(CfmlValue::Int(perf_now_ns()))
}

// ---------------------------------------------------------------------------
// CFML execution
// ---------------------------------------------------------------------------

struct ExecResult {
    output:       String,
    status:       Option<(u16, String)>,
    headers:      Vec<(String, String)>,
    content_type: Option<String>,
    redirect_url: Option<String>,
}

fn execute(
    cfm_path:  &str,
    source:    &str,
    url_scope: IndexMap<String, CfmlValue>,
    cgi_scope: IndexMap<String, CfmlValue>,
    form_scope: Option<IndexMap<String, CfmlValue>>,
) -> std::result::Result<ExecResult, String> {
    // Tag pre-processor
    let processed = if tag_parser::has_cfml_tags(source) {
        tag_parser::tags_to_script(source)
    } else {
        source.to_string()
    };

    // Parse
    let ast = Parser::new(processed)
        .parse()
        .map_err(|e| format!("Parse error at line {}, col {}: {}", e.line, e.column, e.message))?;

    // Compile
    let program = CfmlCompiler::new().compile(ast);

    // VM setup
    let mut vm = CfmlVirtualMachine::new(program);

    // Builtins
    for (name, value) in get_builtins() {
        vm.globals.insert(name, value);
    }
    for (name, func) in get_builtin_functions() {
        vm.builtins.insert(name, func);
    }

    // Override time-dependent builtins: stdlib versions call SystemTime::now()
    // which panics on Workers. Replace with JS Date.now()-backed equivalents.
    #[cfg(target_arch = "wasm32")]
    vm.register_native_fn("gettickcount", builtin_gettickcount);

    // Embedded VFS so cfinclude / new SomeCFC() / createObject all resolve
    vm.vfs = build_vfs();
    vm.base_template_path = Some(VIRTUAL_ROOT.to_string());
    vm.source_file = Some(format!("{VIRTUAL_ROOT}/{cfm_path}"));

    // Request scopes
    vm.globals.insert("url".into(),  CfmlValue::Struct(Arc::new(url_scope)));
    vm.globals.insert("cgi".into(),  CfmlValue::Struct(Arc::new(cgi_scope)));
    if let Some(form) = form_scope {
        vm.globals.insert("form".into(), CfmlValue::Struct(Arc::new(form)));
    }

    vm.execute().map_err(|e| e.to_string())?;

    Ok(ExecResult {
        output:       vm.get_output(),
        status:       vm.response_status,
        headers:      vm.response_headers,
        content_type: vm.response_content_type,
        redirect_url: vm.redirect_url,
    })
}

// ---------------------------------------------------------------------------
// Worker entry point
// ---------------------------------------------------------------------------

#[event(fetch)]
pub async fn main(mut req: Request, _env: Env, _ctx: Context) -> Result<Response> {
    let method  = req.method();
    let path    = req.path();

    // Attempt to resolve the HTTP path to a CFML file
    let cfm_path = match resolve_cfm(&path) {
        Some(p) => p,
        None => return Response::error("Not Found", 404),
    };

    // Find the source bytes in the embedded table
    let source_bytes = CFML_FILES
        .iter()
        .find(|(p, _)| *p == cfm_path)
        .map(|(_, b)| *b)
        .unwrap(); // resolve_cfm already verified it exists

    let source = String::from_utf8_lossy(source_bytes).to_string();

    // Build scopes from the request
    let url_scope = {
        let query = req.url().ok().and_then(|u| u.query().map(str::to_string)).unwrap_or_default();
        parse_query(&query)
    };

    let cgi_scope = build_cgi_scope(&req);

    let form_scope: Option<IndexMap<String, CfmlValue>> = if method == Method::Post {
        let ct = req.headers().get("content-type").ok().flatten().unwrap_or_default();
        if ct.starts_with("application/x-www-form-urlencoded") {
            let body = req.text().await.unwrap_or_default();
            Some(parse_form_body(&body))
        } else {
            None
        }
    } else {
        None
    };

    // Execute the .cfm file
    match execute(cfm_path, &source, url_scope, cgi_scope, form_scope) {
        Ok(result) => {
            // Handle cflocation redirect
            if let Some(redirect) = result.redirect_url {
                return Response::redirect(redirect.parse().map_err(|_| Error::BadEncoding)?);
            }

            let status = result.status.map(|(code, _)| code).unwrap_or(200);
            let content_type = result
                .content_type
                .unwrap_or_else(|| "text/html; charset=utf-8".into());

            let headers = Headers::new();
            headers.set("Content-Type", &content_type)?;
            for (k, v) in result.headers {
                headers.append(&k, &v)?;
            }

            Ok(Response::ok(result.output)?
                .with_status(status)
                .with_headers(headers))
        }
        Err(msg) => {
            // Return error details as plain text (consider a custom error.cfm later)
            let headers = Headers::new();
            headers.set("Content-Type", "text/plain; charset=utf-8")?;
            Ok(Response::ok(format!("CFML Error\n\n{msg}"))?
                .with_status(500)
                .with_headers(headers))
        }
    }
}
